global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'supplyboost-monitor'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Identity Service
  - job_name: 'identity-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
    scrape_interval: 5s

  # Product Catalog Service
  - job_name: 'product-catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
    scrape_interval: 5s

  # Shopping Cart Service
  - job_name: 'shopping-cart-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    scrape_interval: 5s

  # Order Management Service
  - job_name: 'order-management-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
    scrape_interval: 5s

  # Inventory Service
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
    scrape_interval: 5s

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
    scrape_interval: 5s

  # Shipping Service
  - job_name: 'shipping-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
    scrape_interval: 5s

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8088']
    scrape_interval: 5s

  # Accounting Service
  - job_name: 'accounting-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8089']
    scrape_interval: 5s

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s
