apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
  namespace: supplyboost
type: Opaque
stringData:
  database.username: "supplyboost"
  database.password: "CHANGE_ME_IN_PRODUCTION"
  jwt.secret: "CHANGE_ME_IN_PRODUCTION_USE_A_LONG_RANDOM_STRING_HERE"
