apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: supplyboost
data:
  kafka.bootstrap-servers: "kafka-service:9092"
  elasticsearch.url: "http://elasticsearch-service:9200"
  redis.host: "redis-service"
  redis.port: "6379"
  jaeger.endpoint: "http://jaeger-service:4318/v1/traces"
  prometheus.url: "http://prometheus-service:9090"
